myarticles/config/routes.rb
Rails.application.routes.draw do
  namespace 'api' do
  	namespace 'v1' do
  		resources :articles
  	end
  end
end

myarticles/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myarticles/app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

myarticles/app/controllers/api/v1/articles_controller.rb
module Api
	module V1
		class ArticlesController < ApplicationController

			def index
			articles = Article.order('created_at DESC');
			render json: {status: 'Success', message:'Loaded Articles', data:articles}, status: :OK
			end

			def show
				article = Article.find(params[:id])
				render json: {status: 'Success', message:'Loaded Article', data:article}, status: :OK
			end
	
			def create
				article  = Article.new(article_params)
		
			if article.save
				render json: {status: 'Success', message:'Saved Article', data:article}, status: :OK
			else 
				render json: {status: 'Error', message:'Article Not Saved', data:article.errors}, status: :unprocessable_entity
			end
			end

			def destroy
				article = Article.find(params[:id])
				article.destroy
				render json: {status: 'Success', message:'Article Deleted', data:article}, status: :OK
			end

			def update
				article = Article.find(params[:id])
				if article.update_attributes(article_params)
					render json: {status: 'Success', message:'Updated Article', data:article}, status: :OK

				else
					render json: {status: 'Error', message:'Article Not Updated', data:article.errors}, status: :unprocessable_entity
				end
			end

			private
			def article_params
				params.require(article).permit(:title, :body)
			end
		end
	end
end
 

myarticles/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

myarticles/app/views/myarticle/edit.html.erb
<h1> Edit Article</h1>
<%= form_for  :article, url: article_path(@article), method: :patch  do |f| %>
	<% if @article.errors.any? %>
		<% @article.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

myarticles/app/views/myarticle/index.html.erb
<h1> List of Articles </h1>
<% @articles.each do |article| %>
  <div class="well">
  <h3><%= article.title %></h3>
      <p><%= article.body %></p>
  <%= link_to "Read More", article_path(article), :class => 'btn btn-default' %>
  </div>
<% end %>

myarticles/app/views/myarticle/new.html.erb
<h1> Create Article</h1>
<%= form_for  :article, url: articles_path  do |f| %>
	<% if @article.errors.any? %>
		<% @article.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

myarticles/app/views/myarticle/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.body %></p>
<%= link_to "Edit", edit_article_path(@article), :class => 'btn btn-default' %>
<%= link_to "Delete", article_path(@article), 
      method: :delete,
      data: {confirm: 'Are you sure?'},
      :class => 'btn btn-danger' %>